(()=>{"use strict";
const C=window.WHITESPACE_CONFIG||{},ready=!!(C.supabaseUrl&&C.supabaseKey&&!String(C.supabaseUrl).startsWith("COLE_")),sb=ready?window.supabase.createClient(C.supabaseUrl,C.supabaseKey):null;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let currentUser=null,currentProfile=null,searchType="all",booting=false;
const APP_URL=(C.productionUrl||location.origin+location.pathname).replace(/#.*$/,'');
const toast=(m,type="info")=>{const e=$("#toast");if(!e)return;e.textContent=m;e.className="toast show "+type;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),3800)};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ago=i=>{const s=Math.max(1,(Date.now()-new Date(i))/1000);return s<60?Math.floor(s)+"s":s<3600?Math.floor(s/60)+"min":s<86400?Math.floor(s/3600)+"h":Math.floor(s/86400)+"d"};
const initial=n=>(String(n||"?").trim()[0]||"?").toUpperCase();
const avatar=(p,c="avatar")=>p?.avatar_url?'<img class="'+c+'" src="'+esc(p.avatar_url)+'" alt="">':'<div class="'+c+' fallback">'+esc(initial(p?.display_name))+"</div>";
const errorText=e=>{const m=String(e?.message||e||"Erro desconhecido");if(/Email not confirmed/i.test(m))return"A confirmação de e-mail está ativada no projeto.";if(/invalid login credentials/i.test(m))return"E-mail ou senha incorretos.";if(/user already registered/i.test(m))return"Este e-mail já possui uma conta.";if(/duplicate key/i.test(m)&&/username/i.test(m))return"Esse nome de usuário já está em uso.";if(/rate limit|too many requests|50 seconds/i.test(m))return"O serviço recebeu muitas tentativas. Espere um pouco antes de tentar novamente.";return m};
function showAuth(){document.body.classList.remove("logged");$("#auth-screen").classList.remove("hidden");$("#app").classList.add("hidden");$("#landing-screen")?.classList.remove("hidden");$("#auth-window")?.classList.add("hidden")}
function showApp(){document.body.classList.add("logged");$("#auth-screen").classList.add("hidden");$("#app").classList.remove("hidden")}
function applyTheme(p){const r=document.documentElement;r.style.setProperty("--blue",p?.accent_color||"#58c9f4");r.style.setProperty("--profile",p?.profile_color||"#55c8e8");r.style.setProperty("--scale",p?.font_scale||1);document.body.classList.toggle("compact",!!p?.compact_mode)}
function config(){if(!ready){$("#setup-note").classList.remove("hidden");$("#setup-note").textContent="Configuração do Supabase não encontrada. Confira js/config.js.";}}
async function upload(file,id){if(!file)return null;if(!currentUser||currentUser.id!==id)throw Error("Você precisa estar conectado para enviar uma imagem.");if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>3e6)throw Error("Avatar inválido. Use PNG, JPG ou WebP de até 3 MB.");const ext=file.name.split(".").pop().toLowerCase(),path=id+"/"+crypto.randomUUID()+"."+ext;const{error}=await sb.storage.from("avatars").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return sb.storage.from("avatars").getPublicUrl(path).data.publicUrl}
async function profile(id=currentUser?.id){if(!id)throw Error("Sessão inválida.");const{data,error}=await sb.from("profiles").select("*").eq("id",id).single();if(error)throw error;return data}
function mini(){const p=currentProfile;$("#mini-profile").innerHTML='<div class="mini">'+avatar(p)+'<div><strong>'+esc(p.display_name)+'</strong><small>@'+esc(p.username)+'</small></div></div>';$("#composer-avatar").innerHTML=avatar(p)}
async function boot(){if(booting)return;booting=true;try{if(!sb){showAuth();return}const{data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(!currentUser){showAuth();return}currentProfile=await profile();applyTheme(currentProfile);mini();showApp();$("#status").innerHTML="<i></i> ONLINE";$("#status").classList.add("online");await feed()}catch(e){showAuth();toast(errorText(e),"error")}finally{booting=false}}
function revealMessage(message,type="info"){const e=$("#auth-message");e.textContent=message;e.className="auth-message "+type;e.classList.remove("hidden")}
function authId(name){return name.trim().toLowerCase().replace(/^@/,"");}
function authEmail(name){return authId(name)+"@users.whitespace.invalid";}
async function signup(e){
  e.preventDefault(); if(!sb)return toast("Supabase não está disponível.","error");
  const name=authId($("#signup-name").value),password=$("#signup-password").value;
  if(!/^[a-z0-9_]{3,24}$/.test(name))return toast("O nome deve ter 3–24 caracteres: letras, números ou _.","error");
  if(password.length<8)return toast("A senha precisa ter pelo menos 8 caracteres.","error");
  try{
    const existing=await sb.from("profiles").select("id").eq("username",name).maybeSingle();
    if(existing.data)return toast("Esse nome já está em uso.","error");
    const {data,error}=await sb.auth.signUp({email:authEmail(name),password,options:{data:{display_name:name,username:name}}});
    if(error)throw error;
    if(!data.session){
      revealMessage("O login simples ainda não está ativado no Supabase. Desative a confirmação de e-mail em Authentication → Providers → Email.");
      return;
    }
    currentUser=data.user; currentProfile=await profile(); await boot();
  }catch(e){toast(errorText(e),"error")}
}
async function login(e){
  e.preventDefault(); if(!sb)return;
  const name=authId($("#login-name").value),password=$("#login-password").value;
  if(!/^[a-z0-9_]{3,24}$/.test(name))return toast("Digite um nome válido.","error");
  try{
    const {data,error}=await sb.auth.signInWithPassword({email:authEmail(name),password});
    if(error)throw error;
    currentUser=data.user; await boot();
  }catch(e){toast(/invalid login credentials/i.test(String(e?.message||""))?"Nome ou senha incorretos.":errorText(e),"error")}
}
function postCard(p,bookmarked=false){const likes=p.likes||[],liked=likes.some(x=>x.user_id===currentUser.id);return '<article class="panel post" data-post="'+p.id+'"><div class="post-head">'+avatar(p.profiles)+'<div><strong>'+esc(p.profiles?.display_name||"Usuário")+'</strong><small>@'+esc(p.profiles?.username||"")+' · '+ago(p.created_at)+'</small></div>'+(p.author_id===currentUser.id?'<button class="delete" data-id="'+p.id+'">APAGAR</button>':"")+'</div><p class="post-text">'+esc(p.content).replace(/\n/g,"<br>")+'</p><div class="post-actions"><button class="'+(liked?"liked ":"")+'like" data-id="'+p.id+'">♡ '+likes.length+'</button><button class="comment" data-id="'+p.id+'">COMENTAR</button><button class="'+(bookmarked?"liked ":"")+'bookmark" data-id="'+p.id+'">◇ SALVAR</button></div><div class="comments hidden"></div><form class="comment-form hidden"><input required maxlength="500" placeholder="Escreva um comentário..."><button class="aero-button tiny">ENVIAR</button></form></article>'}
async function feed(){const f=$("#feed");if(!currentUser)return;f.innerHTML='<div class="panel loading">Sincronizando seu universo…</div>';const{data,error}=await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(id,display_name,username,avatar_url),likes(user_id)").order("created_at",{ascending:false}).limit(60);if(error){f.innerHTML='<div class="panel empty">'+esc(errorText(error))+"</div>";return}f.innerHTML=data?.length?data.map(p=>postCard(p)).join(""):'<div class="panel empty">Nenhuma transmissão ainda. Seja a primeira ✦</div>'}
async function like(id){try{const{data}=await sb.from("likes").select("post_id").eq("post_id",id).eq("user_id",currentUser.id).maybeSingle();const q=data?sb.from("likes").delete().eq("post_id",id).eq("user_id",currentUser.id):sb.from("likes").insert({post_id:id,user_id:currentUser.id});const{error}=await q;if(error)throw error;await feed()}catch(e){toast(errorText(e),"error")}}
async function comments(card){const box=$(".comments",card);box.classList.remove("hidden");const{data,error}=await sb.from("comments").select("id,content,created_at,profiles!comments_author_id_fkey(display_name,username,avatar_url)").eq("post_id",card.dataset.post).order("created_at");box.innerHTML=error?esc(errorText(error)):data?.length?data.map(c=>'<div class="comment">'+avatar(c.profiles,"avatar tiny")+'<span><strong>'+esc(c.profiles?.display_name)+'</strong><br>'+esc(c.content)+'</span></div>').join(""):"<small>Nenhum comentário ainda.</small>"}
async function addComment(e){e.preventDefault();const f=e.currentTarget,card=f.closest(".post"),v=$("input",f).value.trim();if(!v)return;const{error}=await sb.from("comments").insert({post_id:card.dataset.post,author_id:currentUser.id,content:v});if(error)toast(errorText(error),"error");else{$("input",f).value="";await comments(card)}}
async function bookmark(id){try{const{data}=await sb.from("bookmarks").select("post_id").eq("post_id",id).eq("user_id",currentUser.id).maybeSingle();const{error}=data?await sb.from("bookmarks").delete().eq("post_id",id).eq("user_id",currentUser.id):await sb.from("bookmarks").insert({post_id:id,user_id:currentUser.id});if(error)throw error;toast(data?"Removido dos salvos.":"Salvo na sua coleção.","success")}catch(e){toast(errorText(e),"error")}}
async function deletePost(id){if(!confirm("Apagar esta publicação?"))return;const{error}=await sb.from("posts").delete().eq("id",id);if(error)toast(errorText(error),"error");else await feed()}
async function search(){const q=$("#search-input").value.trim();if(!q){$("#search-results").innerHTML="";return}const safe=q.replace(/[,%]/g,""),people=searchType!=="posts"?await sb.from("profiles").select("id,display_name,username,bio,avatar_url").or("display_name.ilike.%"+safe+"%,username.ilike.%"+safe+"%").limit(20):{data:[]},posts=searchType!=="people"?await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id)").ilike("content","%"+safe+"%").order("created_at",{ascending:false}).limit(30):{data:[]};const peopleHtml=people.data?.map(x=>'<button class="person" data-profile="'+x.id+'">'+avatar(x)+'<div><strong>'+esc(x.display_name)+'</strong><small>@'+esc(x.username)+'</small></div></button>').join("")||'<div class="panel empty">Nenhuma pessoa encontrada.</div>';const postHtml=posts.data?.map(x=>postCard(x)).join("")||'<div class="panel empty">Nenhuma publicação encontrada.</div>';$("#search-results").innerHTML='<div class="result-group"><h3>PESSOAS</h3>'+peopleHtml+'</div><div class="result-group"><h3>PUBLICAÇÕES</h3>'+postHtml+"</div>";$$("[data-profile]").forEach(b=>b.onclick=async()=>{await renderProfile(b.dataset.profile);view("profile")})}
async function renderProfile(id=currentUser.id){try{const p=id===currentUser.id?currentProfile:await profile(id),{data:posts,error}=await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id)").eq("author_id",id).order("created_at",{ascending:false}).limit(50);if(error)throw error;let following=false;if(id!==currentUser.id){const q=await sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("following_id",id).maybeSingle();following=!!q.data}$("#profile-page").innerHTML='<div class="profile-cover panel" style="--profile-bg:'+esc(p.profile_color||"#55c8e8")+'"></div><div class="panel profile-card"><div>'+avatar(p,"profile-avatar")+'</div><div class="profile-info"><div class="profile-title"><div><h2>'+esc(p.display_name)+'</h2><p>@'+esc(p.username)+'</p></div>'+(id===currentUser.id?'<button class="aero-button" data-edit>EDITAR PERFIL</button>':'<button class="aero-button '+(following?"primary":"")+'" data-follow="'+id+'">'+(following?"SEGUINDO":"SEGUIR")+"</button>")+'</div><p class="bio">'+esc(p.bio||"Sem bio ainda.")+'</p><div class="chips"><span><b>'+(posts?.length||0)+'</b> POSTS</span><span>'+esc(p.theme||"ocean").toUpperCase()+"</span></div></div></div><div class="feed">'+(posts?.map(x=>postCard(x)).join("")||'<div class="panel empty">Nenhum post ainda.</div>')+"</div>";$("#profile-page").onclick=async e=>{const f=e.target.closest("[data-follow]");if(f){const target=f.dataset.follow,q=await sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("following_id",target).maybeSingle();const{error}=q.data?await sb.from("follows").delete().eq("follower_id",currentUser.id).eq("following_id",target):await sb.from("follows").insert({follower_id:currentUser.id,following_id:target});if(error)toast(errorText(error),"error");else await renderProfile(target)}if(e.target.closest("[data-edit]"))view("settings")}}catch(e){toast(errorText(e),"error")}}
async function bookmarks(){const{data,error}=await sb.from("bookmarks").select("post_id,posts!bookmarks_post_id_fkey(id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id))").eq("user_id",currentUser.id).order("created_at",{ascending:false});$("#bookmarks-list").innerHTML=error?'<div class="panel empty">'+esc(errorText(error))+"</div>":data?.length?'<div class="feed">'+data.map(x=>postCard(x.posts,true)).join("")+"</div>":'<div class="panel empty">Sua coleção está vazia.</div>'}
function settings(){const p=currentProfile;$("#settings-page").innerHTML='<div class="settings-grid"><div class="panel settings-card"><span class="kicker">PROFILE_EDITOR</span><h2>Seu universo</h2><form id="profile-form" class="form"><label>NOME<input id="edit-name" maxlength="40" value="'+esc(p.display_name)+'" required></label><label>USUÁRIO<input id="edit-user" maxlength="24" value="'+esc(p.username)+'" required></label><label>BIO<textarea id="edit-bio" maxlength="180" rows="4">'+esc(p.bio||"")+'</textarea></label><label>AVATAR <span class="optional">PNG/JPG/WebP · até 3 MB</span><input id="edit-avatar" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="color-row"><label>COR DO PERFIL<input id="edit-color" type="color" value="'+esc(p.profile_color||"#55c8e8")+'"></label><label>COR DE DESTAQUE<input id="edit-accent" type="color" value="'+esc(p.accent_color||"#58c9f4")+'"></label></div><label>TEMA<select id="edit-theme"><option value="ocean">Ocean Terminal</option><option value="aero">Frutiger Aero</option><option value="sunset">Retro Sunset</option><option value="mono">Monochrome</option></select></label><label>TAMANHO DA FONTE<input id="edit-scale" type="range" min=".9" max="1.2" step=".05" value="'+esc(p.font_scale||1)+'"></label><label><input id="edit-compact" type="checkbox" '+(p.compact_mode?"checked":"")+'> Interface compacta</label><button class="aero-button primary">SALVAR ALTERAÇÕES →</button></form></div><div class="panel settings-card"><span class="kicker">ACCOUNT_SECURITY</span><h2>Conta protegida</h2><p class="muted">'+esc(currentUser.email||"")+'</p><p class="muted">Autenticação, sessões e permissões são gerenciadas pelo Supabase Auth e RLS.</p><button id="reset-settings" class="aero-button">ENVIAR RECUPERAÇÃO DE SENHA</button></div></div>';$("#edit-theme").value=p.theme||"ocean";$("#profile-form").onsubmit=saveSettings;$("#reset-settings").onclick=reset}
async function saveSettings(e){e.preventDefault();try{let av=currentProfile.avatar_url;if($("#edit-avatar").files[0])av=await upload($("#edit-avatar").files[0],currentUser.id);const u=$("#edit-user").value.trim().replace(/^@/,"").toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(u))throw Error("Usuário inválido.");const patch={display_name:$("#edit-name").value.trim(),username:u,bio:$("#edit-bio").value.trim(),avatar_url:av,profile_color:$("#edit-color").value,accent_color:$("#edit-accent").value,theme:$("#edit-theme").value,font_scale:Number($("#edit-scale").value),compact_mode:$("#edit-compact").checked};const{data,error}=await sb.from("profiles").update(patch).eq("id",currentUser.id).select().single();if(error)throw error;currentProfile=data;applyTheme(data);mini();toast("Seu universo foi salvo ✦","success");settings()}catch(e){toast(errorText(e),"error")}}
async function notifications(){const{data,error}=await sb.from("notifications").select("type,created_at,actor_id,profiles!notifications_actor_id_fkey(display_name,username)").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(50);$("#notifications-list").innerHTML='<div class="panel settings-card"><span class="kicker">SIGNAL_LOG</span><h2>Notificações</h2>'+(error?esc(errorText(error)):data?.length?data.map(n=>'<p>◇ '+esc(n.type)+' · '+esc(n.profiles?.display_name||"sistema")+' · '+ago(n.created_at)+"</p>").join(""):'<p class="muted">Nenhum sinal novo.</p>')+"</div>"}
function view(v){const titles={home:"INÍCIO",explore:"EXPLORAR",profile:"MEU PERFIL",bookmarks:"SALVOS",notifications:"SINAIS",settings:"CUSTOMIZAR"};$$(".view").forEach(x=>x.classList.add("hidden"));$("#view-"+v).classList.remove("hidden");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#view-title").textContent=titles[v]||v;if(v==="profile")renderProfile();if(v==="bookmarks")bookmarks();if(v==="settings")settings();if(v==="notifications")notifications()}
function openAccess(mode="login"){$("#landing-screen")?.classList.add("hidden");$("#auth-window")?.classList.remove("hidden");$("[data-auth]").forEach(x=>x.classList.toggle("active",x.dataset.auth===mode));$("#signup-form").classList.toggle("hidden",mode!=="signup");$("#login-form").classList.toggle("hidden",mode!=="login");$("#auth-message").classList.add("hidden");(mode==="login"?$("#login-name"):$("#signup-name"))?.focus()}
$("#open-login").onclick=()=>openAccess("login");$("#open-signup").onclick=()=>openAccess("signup");$("#back-auth").onclick=()=>showAuth();
$("[data-auth]").forEach(b=>b.onclick=()=>openAccess(b.dataset.auth));
$$(".nav").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#signup-form").onsubmit=signup;$("#login-form").onsubmit=login;$("#logout").onclick=async()=>{await sb?.auth.signOut();currentUser=null;currentProfile=null;showAuth()};$("#refresh").onclick=feed;$("#search-btn").onclick=search;$("#search-input").onkeydown=e=>{if(e.key==="Enter")search()};$("#post-content").oninput=e=>$("#post-count").textContent=e.target.value.length+" / 1000";
$$("[data-search-type]").forEach(b=>b.onclick=()=>{$$("[data-search-type]").forEach(x=>x.classList.remove("active"));b.classList.add("active");searchType=b.dataset.searchType;search()});
$("#post-form").onsubmit=async e=>{e.preventDefault();const c=$("#post-content").value.trim();if(!c)return;const{error}=await sb.from("posts").insert({author_id:currentUser.id,content:c});if(error)toast(errorText(error),"error");else{$("#post-content").value="";$("#post-count").textContent="0 / 1000";await feed()}};
document.addEventListener("click",e=>{const l=e.target.closest(".like"),b=e.target.closest(".bookmark"),c=e.target.closest(".comment"),d=e.target.closest(".delete");if(l)like(l.dataset.id);if(b)bookmark(b.dataset.id);if(c){const card=c.closest(".post");comments(card);$(".comment-form",card).classList.toggle("hidden")}if(d)deletePost(d.dataset.id)});
document.addEventListener("submit",e=>{if(e.target.matches(".comment-form"))addComment(e)});
$("#quick-theme").onclick=async()=>{if(!currentProfile)return;const themes=["ocean","aero","sunset","mono"],i=themes.indexOf(currentProfile.theme||"ocean"),theme=themes[(i+1)%themes.length];const{data,error}=await sb.from("profiles").update({theme}).eq("id",currentUser.id).select().single();if(error)toast(errorText(error),"error");else{currentProfile=data;applyTheme(data);settings();toast("Tema: "+theme,"success")}};
$("#donate-open").onclick=()=>{$("#donation-options").innerHTML=[5,10,20,50,100].map(a=>C.donations?.[a]?'<a class="donation" target="_blank" rel="noopener noreferrer" href="'+esc(C.donations[a])+'">R$ '+a+"</a>":'<span class="donation disabled">R$ '+a+"</span>").join("");$("#donate-dialog").showModal()};$("#donate-close").onclick=()=>$("#donate-dialog").close();
config();if(sb)sb.auth.onAuthStateChange(()=>setTimeout(boot,0));boot();
})();