(()=>{"use strict";
const C=window.WHITESPACE_CONFIG||{},ready=!!(C.supabaseUrl&&C.supabaseKey&&!C.supabaseUrl.startsWith("COLE_")),sb=ready?window.supabase.createClient(C.supabaseUrl,C.supabaseKey):null;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let currentUser=null,currentProfile=null,searchType="all";
const toast=(m,type="info")=>{const e=$("#toast");if(!e)return;e.textContent=m;e.className="toast show "+type;clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),3200)};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])),ago=i=>{const s=Math.max(1,(Date.now()-new Date(i))/1000);return s<60?Math.floor(s)+"s":s<3600?Math.floor(s/60)+"min":s<86400?Math.floor(s/3600)+"h":Math.floor(s/86400)+"d"},initial=n=>(n||"?").trim()[0]?.toUpperCase()||"?";
const avatar=(p,c="avatar")=>p?.avatar_url?'<img class="'+c+'" src="'+esc(p.avatar_url)+'" alt="">':'<div class="'+c+' fallback">'+esc(initial(p?.display_name))+"</div>";
function showAuth(){$("#auth-screen").classList.remove("hidden");$("#app").classList.add("hidden")}function showApp(){$("#auth-screen").classList.add("hidden");$("#app").classList.remove("hidden")}
function applyTheme(p){const r=document.documentElement;r.style.setProperty("--cyan",p?.accent_color||"#74f7ff");r.style.setProperty("--profile",p?.profile_color||"#08263b");r.style.setProperty("--scale",p?.font_scale||1);document.body.classList.toggle("compact",!!p?.compact_mode)}
function config(){if(!ready){$("#setup-note").classList.remove("hidden");$("#setup-note").textContent="WhiteSpace não encontrou uma configuração válida do Supabase."}}
async function upload(file,id){if(!file)return null;if(!currentUser||currentUser.id!==id)throw Error("Você precisa estar conectado para enviar uma imagem.");if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>3e6)throw Error("Imagem inválida: PNG/JPG/WebP até 3 MB.");const ext=file.name.split(".").pop().toLowerCase(),path=id+"/"+crypto.randomUUID()+"."+ext;const{error}=await sb.storage.from("avatars").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return sb.storage.from("avatars").getPublicUrl(path).data.publicUrl}
async function profile(id=currentUser.id){const{data,error}=await sb.from("profiles").select("*").eq("id",id).single();if(error)throw error;return data}
function mini(){const p=currentProfile;$("#mini-profile").innerHTML='<div class="mini">'+avatar(p)+'<div><strong>'+esc(p.display_name)+'</strong><small>@'+esc(p.username)+'</small></div></div>'}
async function boot(){if(!sb)return showAuth();const{data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(!currentUser)return showAuth();try{currentProfile=await profile();applyTheme(currentProfile);mini();showApp();$("#status").textContent="ONLINE";$("#status").classList.add("online");await feed()}catch(e){toast(e.message,"error")}}
async function signup(e){e.preventDefault();if(!sb)return toast("Supabase não está disponível.","error");const name=$("#signup-name").value.trim(),username=$("#signup-username").value.trim().replace(/^@/,"").toLowerCase(),email=$("#signup-email").value.trim(),password=$("#signup-password").value,file=$("#signup-avatar").files[0];if(!/^[a-z0-9_]{3,24}$/.test(username))return toast("Usuário: 3–24 caracteres, letras minúsculas, números ou _.","error");try{const{data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name,username}}});if(error)throw error;if(!data.session){return toast(file?"Conta criada. Confirme o e-mail e depois entre para enviar seu avatar.":"Conta criada. Confirme o e-mail para entrar.","info")}currentUser=data.user;currentProfile=await profile();if(file){try{const av=await upload(file,currentUser.id);const{data:updated,error:updateError}=await sb.from("profiles").update({avatar_url:av}).eq("id",currentUser.id).select().single();if(updateError)throw updateError;currentProfile=updated}catch(uploadError){toast("Conta criada, mas o avatar não foi enviado: "+uploadError.message,"error")}}await boot()}catch(e){toast(e.message,"error")}}
async function login(e){e.preventDefault();try{const{error}=await sb.auth.signInWithPassword({email:$("#login-email").value.trim(),password:$("#login-password").value});if(error)throw error;await boot()}catch(e){toast(e.message,"error")}}
async function reset(){const email=$("#login-email").value.trim();if(!email)return toast("Digite seu e-mail primeiro.","error");const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href});toast(error?error.message:"Link enviado.","info")}
function postCard(p,bookmarked=false){const liked=(p.likes||[]).some(x=>x.user_id===currentUser.id),n=(p.likes||[]).length;return '<article class="glass post" data-post="'+p.id+'"><div class="post-head">'+avatar(p.profiles)+'<div><strong>'+esc(p.profiles?.display_name)+'</strong><small>@'+esc(p.profiles?.username)+' · '+ago(p.created_at)+'</small></div>'+(p.author_id===currentUser.id?'<button class="text-btn delete" data-id="'+p.id+'">APAGAR</button>':"")+'</div><p class="post-text">'+esc(p.content).replace(/\n/g,"<br>")+'</p><div class="post-actions"><button class="'+(liked?"liked ":"")+"like"+'" data-id="'+p.id+'">♡ '+n+'</button><button class="comment" data-id="'+p.id+'">COMENTAR</button><button class="'+(bookmarked?"liked ":"")+"bookmark"+'" data-id="'+p.id+'">🔖</button></div><div class="comments hidden"></div><form class="comment-form hidden"><input required maxlength="500" placeholder="comentário..."><button class="btn small">ENVIAR</button></form></article>'}
async function feed(){const f=$("#feed");f.innerHTML='<div class="glass loading">SINCRONIZANDO...</div>';const{data,error}=await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(id,display_name,username,avatar_url),likes(user_id)").order("created_at",{ascending:false}).limit(60);if(error)return f.innerHTML='<div class="glass empty">'+esc(error.message)+"</div>";f.innerHTML=data?.length?data.map(p=>postCard(p)).join(""):'<div class="glass empty">Nenhuma transmissão ainda. Seja a primeira. ✦</div>'}
async function like(id){const q=sb.from("likes").select("post_id").eq("post_id",id).eq("user_id",currentUser.id),{data}=await q.maybeSingle();if(data)await sb.from("likes").delete().eq("post_id",id).eq("user_id",currentUser.id);else await sb.from("likes").insert({post_id:id,user_id:currentUser.id});feed()}
async function comments(card){const id=card.dataset.post,box=$(".comments",card);box.classList.remove("hidden");const{data,error}=await sb.from("comments").select("id,content,created_at,profiles!comments_author_id_fkey(display_name,username,avatar_url)").eq("post_id",id).order("created_at");box.innerHTML=error?esc(error.message):data?.length?data.map(c=>'<div class="comment">'+avatar(c.profiles,"avatar tiny")+'<span><strong>'+esc(c.profiles.display_name)+'</strong><br>'+esc(c.content)+'</span></div>').join(""):"<small>Nenhum comentário.</small>"}
async function addComment(e){e.preventDefault();const f=e.currentTarget,card=f.closest(".post"),v=$("input",f).value.trim();if(!v)return;const{error}=await sb.from("comments").insert({post_id:card.dataset.post,author_id:currentUser.id,content:v});if(error)toast(error.message,"error");else{$("input",f).value="";comments(card)}}
async function bookmark(id){const{data}=await sb.from("bookmarks").select("post_id").eq("post_id",id).eq("user_id",currentUser.id).maybeSingle();if(data)await sb.from("bookmarks").delete().eq("post_id",id).eq("user_id",currentUser.id);else await sb.from("bookmarks").insert({post_id:id,user_id:currentUser.id});toast(data?"Removido dos salvos.":"Salvo na sua coleção.","info")}
async function deletePost(id){if(!confirm("Apagar esta publicação?"))return;const{error}=await sb.from("posts").delete().eq("id",id);if(error)toast(error.message,"error");else feed()}
async function search(){const q=$("#search-input").value.trim().replace(/[,%]/g,"");if(!q)return;const people=searchType!=="posts"?await sb.from("profiles").select("id,display_name,username,bio,avatar_url").or("display_name.ilike.%"+q+"%,username.ilike.%"+q+"%").limit(20):{data:[]};const posts=searchType!=="people"?await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id)").ilike("content","%"+q+"%").limit(30):{data:[]};$("#search-results").innerHTML='<div class="result-group"><h2>PESSOAS</h2>'+(people.data?.map(x=>'<button class="glass person" data-profile="'+x.id+'">'+avatar(x)+'<div><strong>'+esc(x.display_name)+'</strong><small>@'+esc(x.username)+'</small></div></button>').join("")||"<p class='muted'>Nada encontrado.</p>")+'</div><div class="result-group"><h2>PUBLICAÇÕES</h2>'+(posts.data?.map(x=>postCard(x)).join("")||"<p class='muted'>Nada encontrado.</p>")+"</div>";$$("[data-profile]").forEach(b=>b.onclick=async()=>{await renderProfile(b.dataset.profile);view("profile")})}
async function renderProfile(id=currentUser.id){const p=id===currentUser.id?currentProfile:await profile(id);const{data:posts}=await sb.from("posts").select("id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id)").eq("author_id",id).order("created_at",{ascending:false}).limit(50);let following=false;if(id!==currentUser.id){const q=await sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("following_id",id).maybeSingle();following=!!q.data}$("#profile-page").innerHTML='<div class="profile-cover glass" style="--profile-bg:'+esc(p.profile_color||"#08263b")+'"></div><div class="glass profile-card"><div>'+avatar(p,"profile-avatar")+'</div><div class="profile-info"><div class="profile-title"><div><h2>'+esc(p.display_name)+'</h2><p>@'+esc(p.username)+'</p></div>'+(id===currentUser.id?'<button class="btn" data-edit>EDITAR</button>':'<button class="btn '+(following?"primary":"")+'" data-follow="'+id+'">'+(following?"SEGUINDO":"SEGUIR")+"</button>")+'</div><p class="bio">'+esc(p.bio||"Sem bio.")+'</p><div class="chips"><span><b>'+(posts?.length||0)+'</b> POSTS</span><span>'+esc(p.theme||"ocean").toUpperCase()+"</span></div></div></div><div class="feed">"+(posts?.map(x=>postCard(x)).join("")||'<div class="glass empty">Nenhum post.</div>')+"</div>";$("#profile-page").onclick=async e=>{const f=e.target.closest("[data-follow]");if(f){const id=f.dataset.follow;const q=await sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("following_id",id).maybeSingle();if(q.data)await sb.from("follows").delete().eq("follower_id",currentUser.id).eq("following_id",id);else await sb.from("follows").insert({follower_id:currentUser.id,following_id:id});renderProfile(id)}if(e.target.closest("[data-edit]"))view("settings")}}
async function bookmarks(){const{data,error}=await sb.from("bookmarks").select("post_id,posts!bookmarks_post_id_fkey(id,content,created_at,author_id,profiles!posts_author_id_fkey(display_name,username,avatar_url),likes(user_id))").eq("user_id",currentUser.id).order("created_at",{ascending:false});$("#bookmarks-list").innerHTML=error?'<div class="glass empty">'+esc(error.message)+"</div>":data?.length?'<div class="feed">'+data.map(x=>postCard(x.posts,true)).join("")+'</div>':'<div class="glass empty">Sua coleção está vazia.</div>'}
function settings(){const p=currentProfile;$("#settings-page").innerHTML='<div class="settings-grid"><div class="glass settings-card"><div class="eyebrow">PROFILE_EDITOR</div><h2>SEU UNIVERSO</h2><form id="profile-form" class="form"><label>NOME<input id="edit-name" maxlength="40" value="'+esc(p.display_name)+'" required></label><label>USUÁRIO<input id="edit-user" maxlength="24" value="'+esc(p.username)+'" required></label><label>BIO<textarea id="edit-bio" maxlength="180">'+esc(p.bio||"")+'</textarea></label><label>AVATAR<input id="edit-avatar" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="color-row"><label>COR DO PERFIL<input id="edit-color" type="color" value="'+esc(p.profile_color||"#08263b")+'"></label><label>COR DE DESTAQUE<input id="edit-accent" type="color" value="'+esc(p.accent_color||"#74f7ff")+'"></label></div><label>TEMA<select id="edit-theme"><option value="ocean">Ocean Terminal</option><option value="aero">Frutiger Aero</option><option value="sunset">Retro Sunset</option><option value="mono">Monochrome</option></select></label><label>TAMANHO DA FONTE<input id="edit-scale" type="range" min=".9" max="1.2" step=".05" value="'+esc(p.font_scale||1)+'"></label><label><input id="edit-compact" type="checkbox" '+(p.compact_mode?"checked":"")+'> Interface compacta</label><button class="btn primary">SALVAR TUDO →</button></form></div><div class="glass settings-card"><div class="eyebrow">ACCOUNT_SECURITY</div><h2>CONTA PROTEGIDA</h2><p class="muted">'+esc(currentUser.email||"")+'</p><p class="muted">Dados protegidos por Supabase Auth + Row Level Security.</p><button id="reset-settings" class="btn">RECUPERAR SENHA</button></div></div>';$("#edit-theme").value=p.theme||"ocean";$("#profile-form").onsubmit=saveSettings;$("#reset-settings").onclick=reset}
async function saveSettings(e){e.preventDefault();try{let av=currentProfile.avatar_url;if($("#edit-avatar").files[0])av=await upload($("#edit-avatar").files[0],currentUser.id);const u=$("#edit-user").value.trim().replace(/^@/,"").toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(u))throw Error("Usuário inválido.");const patch={display_name:$("#edit-name").value.trim(),username:u,bio:$("#edit-bio").value.trim(),avatar_url:av,profile_color:$("#edit-color").value,accent_color:$("#edit-accent").value,theme:$("#edit-theme").value,font_scale:Number($("#edit-scale").value),compact_mode:$("#edit-compact").checked};const{data,error}=await sb.from("profiles").update(patch).eq("id",currentUser.id).select().single();if(error)throw error;currentProfile=data;applyTheme(data);mini();toast("Seu universo foi salvo ✦");settings()}catch(e){toast(e.message,"error")}}
async function notifications(){const{data,error}=await sb.from("notifications").select("type,created_at,actor_id,profiles!notifications_actor_id_fkey(display_name,username)").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(50);$("#notifications-list").innerHTML='<div class="glass settings-card"><div class="eyebrow">SIGNAL_LOG</div><h2>NOTIFICAÇÕES</h2>'+(error?esc(error.message):data?.length?data.map(n=>'<p>◇ '+esc(n.type)+' · '+esc(n.profiles?.display_name||"sistema")+' · '+ago(n.created_at)+"</p>").join(""):"<p class='muted'>Nenhum sinal novo.</p>")+"</div>"}
function view(v){const titles={home:"INÍCIO",explore:"EXPLORAR",profile:"MEU PERFIL",bookmarks:"SALVOS",notifications:"SINAIS",settings:"CUSTOM"};$$(".view").forEach(x=>x.classList.add("hidden"));$("#view-"+v).classList.remove("hidden");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#view-title").textContent=titles[v];if(v==="profile")renderProfile();if(v==="bookmarks")bookmarks();if(v==="settings")settings();if(v==="notifications")notifications()}
$$("[data-auth]").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#signup-form").classList.toggle("hidden",b.dataset.auth!=="signup");$("#login-form").classList.toggle("hidden",b.dataset.auth!=="login")});
$$(".nav").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#signup-form").onsubmit=signup;$("#login-form").onsubmit=login;$("#forgot-password").onclick=reset;$("#logout").onclick=async()=>{await sb?.auth.signOut();showAuth()};$("#refresh").onclick=feed;$("#search-btn").onclick=search;$("#search-input").onkeydown=e=>{if(e.key==="Enter")search()};$("#post-content").oninput=e=>$("#post-count").textContent=e.target.value.length+"/1000";
$$("[data-search-type]").forEach(b=>b.onclick=()=>{$$("[data-search-type]").forEach(x=>x.classList.remove("active"));b.classList.add("active");searchType=b.dataset.searchType;search()});
$("#post-form").onsubmit=async e=>{e.preventDefault();const c=$("#post-content").value.trim();if(!c)return;const{error}=await sb.from("posts").insert({author_id:currentUser.id,content:c});if(error)toast(error.message,"error");else{$("#post-content").value="";$("#post-count").textContent="0/1000";feed()}};
document.addEventListener("click",e=>{const l=e.target.closest(".like"),b=e.target.closest(".bookmark"),c=e.target.closest(".comment"),d=e.target.closest(".delete");if(l)like(l.dataset.id);if(b)bookmark(b.dataset.id);if(c){const card=c.closest(".post");comments(card);$(".comment-form",card).classList.toggle("hidden")}if(d)deletePost(d.dataset.id)});
document.addEventListener("submit",e=>{if(e.target.matches(".comment-form"))addComment(e)});
$("#quick-theme").onclick=()=>{const themes=["ocean","aero","sunset","mono"],i=themes.indexOf(currentProfile.theme||"ocean"),theme=themes[(i+1)%themes.length];sb.from("profiles").update({theme}).eq("id",currentUser.id).then(()=>{currentProfile.theme=theme;toast("Tema: "+theme);settings()})};
$("#donate-open").onclick=()=>{$("#donation-options").innerHTML=[5,10,20,50,100].map(a=>C.donations?.[a]?'<a class="donation" target="_blank" rel="noopener" href="'+esc(C.donations[a])+'">R$ '+a+"</a>":'<span class="donation disabled">R$ '+a+"</span>").join("");$("#donate-dialog").showModal()};$("#donate-close").onclick=()=>$("#donate-dialog").close();
config();if(sb)sb.auth.onAuthStateChange(()=>setTimeout(boot,0));boot();
})();